# Generated by Django 5.1.3 on 2024-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_question',
            fields=[
                ('question_number', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=300)),
                ('answer', models.TextField(max_length=2000)),
            ],
        ),
    ]
